services:
  janus:
    image: 'sucwangsr/janus-webrtc-gateway-docker:1.3.0-slim'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    # build: ./janus
    # command: /opt/janus/bin/janus
    volumes:
      - ./janus/certs:/opt/certs
      - ./data:/opt/data
      - type: bind
        source: ./janus/config/janus.transport.http.jcfg
        # target: /opt/janus/etc/janus/janus.transport.http.jcfg
        target: /usr/local/etc/janus/janus.transport.http.jcfg
      - type: bind
        source: ./janus/config/janus.transport.websockets.jcfg
        # target: /opt/janus/etc/janus/janus.transport.websockets.jcfg
        target: /usr/local/etc/janus/janus.transport.websockets.jcfg
      - type: bind
        source: ./janus/config/janus.plugin.streaming.jcfg
        # target: /opt/janus/etc/janus/janus.plugin.streaming.jcfg
        target: /usr/local/etc/janus/janus.plugin.streaming.jcfg
    ports:
      - "5000-5100:5000-5100/udp" # rtp input
      # - "7088:7088" # admin
      # - "7889:7889" # admin secure
      - "8088:8088" # general
      - "8089:8089" # general secure
      - "8188:8188" # ws
      - "8989:8989" # wss
      # - "10000-10200:10000-10200/udp" # streaming rtp
  janus-interface:
    image: node:23-bullseye
    working_dir: /app
    command: bash -c "yarn && yarn dev"
    volumes:
      - ./janus-interface:/app
    ports:
      - 3000:3000
  janus-interface-webpack:
    image: node:23-bullseye
    working_dir: /app
    command: bash -c "yarn && npx --yes webpack serve"
    volumes:
      - ./janus-interface-webpack:/app
    ports:
      - 3001:3001
    environment:
      - PORT=3001
    #   - HTTPS=true
    #   - JANUS_HOST=your-janus-server.com
    #   - ICE_URL=turn:your-ice-server.com:3478
    #   - ICE_USERNAME=your-ice-username
    #   - ICE_PASSWORD=your-ice-password
  janus-interface-webpack-2:
    image: node:23-bullseye
    working_dir: /app
    command: bash -c "yarn && npx --yes webpack serve"
    volumes:
      - ./janus-interface-webpack-2:/app
    ports:
      - 3002:3002
    environment:
      - PORT=3002
    #   - HTTPS=true
    #   - JANUS_HOST=your-janus-server.com
    #   - ICE_URL=turn:your-ice-server.com:3478
    #   - ICE_USERNAME=your-ice-username
    #   - ICE_PASSWORD=your-ice-password
  janus-sample-front:
    build: ./janus-sample-front
    command: bash -c "cd /app/janus-gateway/html && ws --http2"
    volumes:
      - type: bind
        source: ./janus-sample-front
        target: /app
    ports:
      - "8000:8000"
